apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "kr.co.nicevan.androidnvcat"
        minSdkVersion 22
        targetSdkVersion 26
        versionCode 1
        versionName '1.0.48'
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "armeabi"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions { //시리얼사용을위해 1.8이상
        encoding "UTF-8"
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    sourceSets {
        main {
            assets.srcDir("src/main/assets")
        }
    }
    namespace 'kr.co.nicevan.androidnvcat'
    /*
    //https://dlehdgml0480.tistory.com/3
    packagingOptions {
        exclude 'lib/x86_64/darwin/libscrypt.dylib'
        exclude 'lib/x86_64/freebsd/libscrypt.so'
        exclude 'lib/x86_64/linux/libscrypt.so'
    }
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64', 'arm64-v8a'
            universalApk false
        }
    }
    */
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    implementation project(':library')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //OSM20250805 : Lifecycle, LiveData, ViewModel 관련 의존성 추가 (SDK Version 26으로 변경함에 따른 수정)
    implementation "android.arch.lifecycle:extensions:1.1.1"

    //implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:appcompat-v7:26.1.0'
    //implementation 'androidx.appcompat:appcompat:1.6.1'

    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    //implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:support-v4:26.1.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation files('libs/nicepos.jar') //jar 로드
    implementation files('libs/libokpos.jar') //jar 로드
    implementation files('libs/niceposdown.jar') //jar 로드
    implementation files('libs/niceposdown.jar') //jar 로드
    implementation files('libs/niceposdown.jar') //jar 로드
    implementation 'com.annimon:stream:1.2.1' //시리얼 통신시 필요
    implementation 'com.squareup.okio:okio:2.1.0' //시리얼 통신시 필요
    implementation 'com.github.gcacace:signature-pad:1.3.1'
    implementation 'com.journeyapps:zxing-android-embedded:3.5.0' //바코드리딩
    implementation 'com.github.mik3y:usb-serial-for-android:2.2.0'
    implementation files('libs/devmelSDK-java1.0.jar')
    implementation project(path: ':zoableservice-release')
}

